### PR TITLE
configure_new_tunnel() Updated

### PR DESCRIPTION
**Pull request by jalalsaberi**
Now it is possible to enter multiple ports in a config at the same time

### CODE REVIEW

**Comment by Musixal** [comment]
I appreciate you work but if the user wants to add multiple destination ip address with your current code it is not possible. Maybe adding a menu option for add a new config is a reasonable approach.

**Comment by jalalsaberi** [comment]
I think you misunderstood. This update is not for adding multiple IPs; it's for adding multiple ports simultaneously on a single IP. This way, in the Configure Tunnel (IPv4/v6) / New Configuration section, you won't have to use this option every time you want to add a port: Do you want to add another config? (yes/no)

Example:

multi-port

**Comment by Musixal** [comment]
I read your codes and commented with correct understanding. You have not yet provided an answer to my question. If the user wants to add another IP, it is possible with the "add another config" in the current version, but in the state you coded, only multi-port support has been added and the possibility of adding another server has been removed.

**Comment by jalalsaberi** [comment]
I updated the code so that users can now add multiple configurations (IPs) with the multi-port feature. Please check it again.

**Review by Musixal — APPROVED** [review]
Thanks. Multiport support added to HAProxy script.

**Pull request merged**
